/* V5 连续叙事：改对白、承接和表演，不改变 V4 的 18 个历史节点。 */
(function(T){
  'use strict';
  const say=(who,text,expression='neutral')=>({kind:'say',who,text,expression});
  const move=(scene,text,duration=1700,extra={})=>({kind:'action',scene,text,duration,...extra});
  const play=(scene,performance,text,duration)=>move(scene,text,duration,{performance});
  const use=(who,text)=>({kind:'activity',who,text,expression:'neutral'});
  const lesson=(who,text,note)=>({kind:'teaching',who,text,note,expression:'positive'});
  const decide=(who,text,options)=>({kind:'choice',who,text,options,expression:'problem'});
  const N={
    invitation:[
      say('thomas','车台收好了。\n明天，我们去哪里演？','problem'),
      move('city-invitation','散场后，演员收拾道具，一位学者带来了书。',2200),
      say('lorenzo','我找到一段古典喜剧。\n愿意一起试着演出来吗？','positive'),
      say('thomas','我们得继续找场地。\n两条路，你想先走哪一条？')
    ],
    events:{},
    props:{
      text:{title:'洛伦佐的古典文本',owner:'lorenzo',text:'书页上是一段古典喜剧，几个人在同一条街上错认彼此。旁边的笔记写着：古人的空间，能不能帮助今天的演出？'},
      invitation:{title:'伊莎贝拉的邀请',owner:'isabella',text:'请来大厅排演，让宾客都看得清楚。图纸可以先看，排练的结果更重要。'},
      sketch:{title:'马泰奥的透视草图',owner:'matteo',text:'街道越往后越小，线条汇向共同的远点。草图角落另写一行：演员请先停在前区。'},
      note:{title:'卢卡的排练批注',owner:'luca',text:'“门在街道深处，我却不能真的走到门前。”表演路线得和布景尺度一起安排。'},
      ledger:{title:'托马斯的账本',owner:'thomas',text:'车费、布料、食宿，一项也不能少。下一页还空着：明天的场地。'},
      notice:{title:'艾格妮丝留下的便条',owner:'agnes',text:'明天有一队客商入住，院子要留给货物。这晚的演出很好，可旅馆不是每天都能成为剧场。'},
      nextplay:{title:'伊莎贝拉的新剧目',owner:'isabella',text:'下个月的故事发生在森林。这次，演员要穿过林间，而不是走过城市街道。'},
      script:{title:'埃德蒙的剧本页',owner:'edmund',text:'前一幕在宫殿，下一幕已到森林，再下一幕军旗出现。场景由台词、动作和少量道具共同建立。'}
    }
  };
  const add=(id,title,props,beats)=>{N.events[id]={title,props,beats};};
  add('ITALY_01_HUMANISM','一本书，怎样变成一场戏？',['text'],[
    say('lorenzo','古典喜剧里的街道还在纸上。\n我们把它搬到眼前试试。','positive'),
    move('it-research','翻开文本，把遗迹草图与测量笔记放到一起。',2000),
    say('matteo','书给了线索，遗迹给了尺度。\n先让我画一张排练图。'),
    lesson('lorenzo','但今天的演员，该站在哪里？','人文主义研究把古典文本、遗迹观察与当代舞台实验联系起来。')
  ]);
  add('ITALY_02_UNIFIED_SPACE','这条街被切成了几块',['text'],[
    move('city-mansions','排练开始，卢卡从一座场景单元走向另一座。',1500),
    say('luca','我只是去街对面。\n怎么像换了一个世界？','problem'),
    decide('lorenzo','这场喜剧发生在同一条街。\n我们怎样让地点接起来？',[
      {text:'把单元摆得更远',effect:'spread-mansions',reply:'距离变大了，街道仍然是断的。',who:'luca'},
      {text:'把几个地点连成同一条街',correct:true},
      {text:'再加一座独立的场景',effect:'extra-mansion',reply:'地点更多了，可人物仍走不通。',who:'lorenzo'}]),
    move('city-unified','分开的场景单元，组织成同一处行动空间。'),
    lesson('lorenzo','街道接上了。\n伊莎贝拉想看看我们的排练。','连续的戏剧地点，推动这里对统一视觉空间的探索。并置式场景仍在其他实践中使用。')
  ]);
  add('ITALY_03_COURT','一封来自大厅的邀请',['invitation'],[
    say('isabella','到我的大厅来试演吧。\n宾客的位置，也请你们安排。'),
    move('it-hall','街头排练移入一处室内大厅。',2300),
    say('matteo','这里可以控制背景和入口。\n不过，宾客还围在四周。'),
    lesson('isabella','明晚就要迎接客人。\n先让我看看，坐在哪里最好。','宫廷和学院的委托，为室内舞台实验提供场地与资源，也影响观看秩序。')
  ]);
  add('ITALY_04_FRONTAL_VIEWING','谁能看到这条完整的街？',['invitation'],[
    say('matteo','这条街是朝一个方向画的。\n背后的客人只看见支架。','problem'),
    decide('isabella','请替宾客安排观看的位置。',[
      {text:'让大家继续围在布景四周',effect:'ring-court',reply:'我绕到后面，只看见木头。',who:'isabella'},
      {text:'让宾客面向同一个舞台方向',correct:true},
      {text:'把观众放在布景后方',effect:'back-seats',reply:'演员和画好的街道都背对我了。',who:'isabella'}]),
    move('it-frontal','席位汇向舞台正面，形成共同观看方向。'),
    lesson('matteo','方向有了。\n现在，让这条短街看起来更深。','正面观看有利于统一构图；观众位置成为舞台设计的一部分。')
  ]);
  add('ITALY_05_PERSPECTIVE','马泰奥画出了一条长街',['sketch'],[
    say('matteo','这间大厅不够深。\n但眼睛可以看见更远的街道。','positive'),
    move('it-perspective','景片沿着舞台后方排开。'),
    use('matteo','替我收拢远处的景片。\n留意它们怎样逐渐变小。'),
    say('luca','看着真远。\n我去街尽头那扇门试试。','positive'),
    lesson('matteo','先看他的排练路线。','递减的景片与共同消失点，能在有限舞台里构造纵深幻觉。')
  ]);
  add('ITALY_06_GIANT_ACTOR_BUG','卢卡成了街上的“巨人”',['sketch','note'],[
    say('luca','我的台词要在那扇门前说。\n我走过去了。'),
    move('it-giant','卢卡保持正常身高，走进不断缩小的景片。',3000),
    say('luca','等等，这扇门只到我的腰！','problem'),
    say('matteo','是我的街道缩小了。\n你的身体可不会跟着缩。','problem'),
    move('it-zones','把表演路线移回前区，后区保留视觉纵深。',1800),
    lesson('luca','我留在前面。\n伊莎贝拉，您坐下看看？','透视布景的缩尺会限制演员深入后区，表演区与幻觉区需要协调。')
  ]);
  add('ITALY_07_VIEWPOINT_BUG','伊莎贝拉换了一个座位',['invitation','sketch'],[
    say('isabella','我想坐到侧边，陪陪客人。'),
    move('it-viewpoint','镜头跟随伊莎贝拉从中央移到侧面。',1700,{camera:'side'}),
    say('isabella','怎么回事？\n街道好像歪了。','problem'),
    say('matteo','它原本对着中央座位。\n请比较一下两个位置。','problem'),
    use('isabella','移动我的座位，看看变化。'),
    lesson('isabella','所以你的城市，\n只对我的座位存在？','这种透视构图依赖理想观看点；不同座位获得的幻觉并不相同。')
  ]);
  add('ITALY_08_FRAMED_STAGE','终于可以好好演一小段',['note'],[
    say('matteo','还得替画面加一道边界。\n把支架和出入口藏到两侧。'),
    move('it-framed','框口集中观看方向，遮住布景的边缘。',2200),
    say('luca','这次，我留在街道前面演。\n诸位，请看！','positive'),
    play('it-framed','italy','卢卡登场、停步、致意；宾客的目光集中到舞台。',4300),
    lesson('isabella','街道、演员和宾客终于配合了。','框口组织视线并遮蔽部分舞台机制。这个示意并非现代镜框舞台的完整复原。')
  ]);
  add('ITALY_09_PERMANENT_THEATRE','把实验留在一座建筑里',['sketch'],[
    say('lorenzo','我们暂时翻到另一个案例。\n看看维琴察的奥林匹克剧场。'),
    move('it-olimpico','跨年代案例：维琴察奥林匹克剧场，1585 年启用。',2300),
    say('matteo','固定的建筑背景与透视街景，\n把这种视觉实验留了下来。'),
    lesson('lorenzo','看过这个案例，回到我们的排练。','奥林匹克剧场结合古典建筑语汇与固定透视街景；它不等于现代镜框舞台的完成形态。')
  ]);
  add('ITALY_10_CHANGEABLE_SCENERY','下一出戏，却发生在森林',['sketch','nextplay'],[
    move('it-changeable-fixed','回到排练场，下一份剧本已经送到。',1300),
    say('isabella','下个月，演一个森林里的故事。\n我把新剧本带来了。','positive'),
    say('luca','这次我要穿过森林。\n可你画的还是一整条街。','problem'),
    say('matteo','那就让画面能换。\n试试把不同景片送进同一舞台。'),
    move('it-changeable','把场景拆成可替换的景片组。'),
    use('matteo','切换城市、宫殿和森林。\n留意框口中的空间怎样改变。'),
    lesson('matteo','这条路，让舞台建立视觉世界。\n去看看英国的伙伴怎样演吧。','换景机制回应剧目变化。这里按问题串联案例，不表示可变布景直到奥林匹克剧场之后才出现。')
  ]);
  add('ENGLAND_01_TRAVELLING_PLAYERS','账本的下一页还是空的',['ledger'],[
    say('thomas','这一站的钱，刚够食宿。\n明天的演出还没有地方。','problem'),
    move('en-players','离开散场的城市，演员带着行李继续上路。',2000),
    say('will','我们能演。\n可总得有人愿意接待。'),
    lesson('thomas','先把人聚齐，再一起找场地。','流动演出依赖接待、许可与收入。持续演出需要相对稳定的组织。')
  ]);
  add('ENGLAND_02_COMPANY','先把人留在一起',['ledger'],[
    say('thomas','只有演员还不够。\n音乐、道具，也得有人照应。'),
    move('en-company','剧团成员从各处聚到一起。'),
    use('thomas','帮我联系协作伙伴。\n人齐了，再去寻找赞助。'),
    say('will','有了伙伴，不必每次重新凑人。','positive'),
    lesson('thomas','我约了一个大厅。\n带上行李，去问问。','职业剧团与贵族庇护有助于组织演出，但不等于自动获得每个城市的许可。')
  ]);
  add('ENGLAND_03_INN_YARD','艾格妮丝腾出了院子',['ledger','notice'],[
    move('en-travel-hall','第一站：大厅已有宴会，今天不能借用。',1800),
    say('thomas','大厅排满了。\n再去市政厅问问。','problem'),
    move('en-town-hall','第二站：市政空间另有安排，众人继续上路。',1800),
    say('will','又没轮到我们。\n天快黑了。','problem'),
    move('en-travel','第三站：艾格妮丝的旅馆院落。',2000),
    say('agnes','今晚院子还空着。\n别挡住客人进出的路。'),
    decide('will','平台放在哪里，大家才好看？',[
      {text:'放在院子入口处',effect:'block-gate',reply:'客人进不来了，把入口空出来。',who:'agnes'},
      {text:'移到院落后端，留下观看空间',correct:true},
      {text:'贴着一侧的客房门',effect:'side-platform',reply:'住客还要出入，平台再挪一挪。',who:'agnes'}]),
    move('en-inn','小平台进入院落，楼廊也成为观看位置。'),
    use('agnes','沿院子移动平台，留出通行处。'),
    say('will','各位，借这方寸之地，\n给你们演一段。','positive'),
    play('en-inn','england','台前、两侧和楼廊都有人回应。',5000),
    say('agnes','客人都围过来了。\n你们这段戏，真让院子热闹起来。','positive'),
    lesson('will','观众离得近，回应也来得快。','临时场地的房间、楼廊和地面，可以被演出重新组织成观看空间。')
  ]);
  add('ENGLAND_04_PUBLIC_THEATRE','成功的一晚，不等于明天',['notice','ledger'],[
    say('agnes','明天客商要住进来。\n院子得还给货物了。','problem'),
    say('thomas','戏能演，地方却留不住。\n我们需要固定演出的场所。','problem'),
    move('en-public','拿院落作空间参照，试想一座专用的公共剧场。'),
    use('thomas','拖动观察：房间转为楼廊，\n围合的空间开始服务于观看。'),
    lesson('will','有了剧场，也得想想怎样面对观众。','1576 年的 The Theatre 是伦敦早期重要公共剧场之一；模型变形并非证明它直接由旅馆改造而来。')
  ]);
  add('ENGLAND_05_THRUST_STAGE','威尔迈进了观众之间',[],[
    say('will','正面有人，侧边也有人。\n我往前走一点。'),
    move('en-thrust','舞台伸入观众之间，演员向前走。',2100),
    use('will','站到我的位置。\n看看左侧、前方和右侧。'),
    lesson('will','一句话，可以说给不同方向的人。','伸入式舞台让观众从多个方向观看，演员的转身、目光与声音共同组织交流。')
  ]);
  add('ENGLAND_06_OPEN_STAGE','埃德蒙又写了一个新地点',['script'],[
    say('edmund','这一幕在宫殿，下一幕去森林。\n再下一幕，军队已经到战场。','positive'),
    say('thomas','每幕都搭一座布景？\n账本可受不了。','problem'),
    decide('will','观众就在旁边。\n我们怎样把他们带到新地方？',[
      {text:'每幕都停下来建一座写实建筑',effect:'full-sets',reply:'搭景的工夫，比这一幕还长。',who:'thomas'},
      {text:'用台词、动作和少量道具转换地点',correct:true},
      {text:'所有场面都留在同一个宫殿',effect:'plan-only',reply:'可人物接下来必须走进森林。',who:'edmund'}]),
    move('en-open','保持开放的表演空间，让关键道具进入。'),
    use('edmund','试着换一个道具，读出一句台词。'),
    lesson('will','地点变了，观众还和我们在一起。','开放舞台可由语言、动作与道具提示地点；这并不意味着当时的剧场完全没有布景。')
  ]);
  add('ENGLAND_07_VERTICAL_COSMOLOGY','舞台，也能容纳一个世界',['script'],[
    say('edmund','还记得广场上不同的场景单元吗？\n空间也能让人联想到不同世界。'),
    move('city-mansions','短暂回望：中世纪并置场景的空间象征。',2000,{camera:'map'}),
    move('en-flashback','回到公共剧场，观察上方、台面和台下。',2100),
    say('will','抬头是天，脚下还有入口。\n故事可以从不同方向出现。'),
    move('en-cosmos','用剖口显示台下，并标出三个层次。'),
    use('edmund','把三个词，放到对应的位置。'),
    lesson('edmund','同一座舞台，容得下更多想象。','Heavens、台面与活板门下的空间可承载象征和舞台效果；与中世纪的对照不证明直接传承。')
  ]);
  add('ENGLAND_08_GLOBE','从借来的院子，到相聚的剧场',['ledger'],[
    say('thomas','这次，场地不再每晚重找。\n观众可以为一场戏聚到这里。','positive'),
    move('en-globe','环球类型公共剧场：楼廊、露天院场与伸入式舞台。',2400),
    say('will','我们带来的不只是一块平台。\n还有和观众一起完成故事的办法。','positive'),
    lesson('will','马泰奥的舞台又怎样？\n把两种办法放在一起看看。','环球剧场于 1599 年建立。此处是类型化教学模型，并非对原建筑的精确复原。')
  ]);
  T.NARRATIVE=N;
})(window.TTM);
